HTTP/1.0 500 Server Error
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>

<head>
    <style>
        * {
            font-family: 'Consolas', sans-serif;
            color: white;
            background: blue;
            font-size: large;
        }

        h3,
        p {
            margin: 0px;
        }

        .console::before {
            content: '>'
        }

        .denied {
            position: absolute;
            right: 50%;
            top: 25%;
        }
    </style>
</head>

<body>
    <h3>Jurassic Park, System Interface</h3>
    <h3>Version 4.0.5, Alpha E</h3>
    <h3>Ready...</h3>
    <h3 id="element"></h3>
    <img hidden class="denied" src="https://media.giphy.com/media/5ftsmLIqktHQA/giphy.gif">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/typeit/5.0.2/typeit.min.js"></script>
    <script type="text/javascript">
        var type = new TypeIt('#element', { cursor: false });
        addCommand(type, 400, 55, `<p class='console'> access main program</p>`);
        addCommand(type, 1300, 65, `<p class='console'> access main security</p>`);
        addCommand(type, 1000, 45, `<p class='console'> access security</p>`);
        addCommand(type, 1000, 45, `<p class='console'> access main security grid</p>`, true);
        magicWord(type);
        setTimeout(() => { document.getElementsByClassName("denied")[0].removeAttribute("hidden"); }, 15000);

        function addCommand(type, pause, speed, command, last) {
            const basicResponse = 'access: PERMISSION DENIED.';
            let response = last ? basicResponse + '....and....' : basicResponse;
            type.pause(pause)
                .options({ speed: speed })
                .type(command)
                .pause(200)
                .options({ speed: 0 })
                .type(response)
                .break();
        }

        function magicWord(type) {
            type.pause(1500);
            for (var index = 0; index < 40; index++) {
                type.pause(4)
                    .options({ speed: 0 })
                    .type(`YOU DIDN'T SAY THE MAGIC WORD!`)
                    .break();
            }
        }
    </script>
</body>

</html>